#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import requests
from bs4 import BeautifulSoup
import re
'''#第一关
url = 'http://www.heibanke.com/lesson/crawler_ex00/'
header = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) \
Chrome/50.0.2661.102 UBrowser/6.1.2107.204 Safari/537.36'}
while True:
    print('current url is %s' %url)
    req_url = requests.get(url=url, headers=header)
    soup = BeautifulSoup(req_url.text, 'lxml')
    newnumber = re.findall("\d+",soup.select('h3')[0].text)
    if newnumber == []:
        print('over')
        print(soup.select('h3')[0].text)
        break
    else:
        url = 'http://www.heibanke.com/lesson/crawler_ex00/' + newnumber[0]
'''
#第二关
url = 'http://www.heibanke.com/lesson/crawler_ex01/'
header = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) \
Chrome/50.0.2661.102 UBrowser/6.1.2107.204 Safari/537.36'}
playload = {'username':'liamxis','password':'1'}
for i in range(31):
    playload['password']= i
    print('传入密码为%s'%i)
    r = requests.post(url,data=playload)
    if '密码错误' not in r.text:
        print('成功了,密码是：%s'%i)
        break
